/* This script has been generated by /home/buck/Documents/software/formulate_graphql/build/make_queries.js.
 * All the exported functions should be imported into another file and set on an
 * instance of graphql-request.GraphQLClient
 */
import { GraphQLClient } from 'graphql-request'

import {ContinentMembersQuery, ContinentMembersQueryVariables, ContinentMembersDocument} from './types'
async function getContinentMembers(this:GraphQLClient, args:ContinentMembersQueryVariables){
	return this.request<ContinentMembersQuery,ContinentMembersQueryVariables>(ContinentMembersDocument,args)
}
import {CountryDetailsQuery, CountryDetailsQueryVariables, CountryDetailsDocument} from './types'
async function getCountryDetails(this:GraphQLClient, args:CountryDetailsQueryVariables){
	return this.request<CountryDetailsQuery,CountryDetailsQueryVariables>(CountryDetailsDocument,args)
}
import {LanguageDetailsQuery, LanguageDetailsQueryVariables, LanguageDetailsDocument} from './types'
async function getLanguageDetails(this:GraphQLClient, args:LanguageDetailsQueryVariables){
	return this.request<LanguageDetailsQuery,LanguageDetailsQueryVariables>(LanguageDetailsDocument,args)
}
import {NamesAndCodesQuery, NamesAndCodesQueryVariables, NamesAndCodesDocument} from './types'
async function getNamesAndCodes(this:GraphQLClient, args:NamesAndCodesQueryVariables){
	return this.request<NamesAndCodesQuery,NamesAndCodesQueryVariables>(NamesAndCodesDocument,args)
}

export default {getContinentMembers,getCountryDetails,getLanguageDetails,getNamesAndCodes};